const catchAsync = require("../utils/catchAsync");


exports.UserList  =  catchAsync(async(req,res)=>{
    try {
        
    } catch (error) {
        console.log("error" ,error)
    }
})